### ISSUE TITLE
Villagers are not sleeping on 1.8.8

### ISSUE THREAD

**Issue by Nutty101** [Nutty101/NPCDestinations_Animation#6]
Players sleep, but Villagers will not.

**Comment by Nutty101** [comment]
𝓗ighest#6669  on discord reported.

**Comment by Nutty101** [comment]
Issue exists in the latest version, but for a new reason.
`[14:59:38 INFO]: [NPCDestinations_Animator] Error:java.lang.ClassCastException: net.citizensnpcs.nms.v1_8_R3.entity.VillagerController$VillagerNPC cannot be cast to org.bukkit.entity.Player
        at net.livecar.nuttyworks.destinations_animations.nms.VersionBridge_1_8_R3.SleepNPC(VersionBridge_1_8_R3.java:39)
        at net.livecar.nuttyworks.destinations_animations.plugin.Processing.SleepCycle(Processing.java:275)
        at net.livecar.nuttyworks.destinations_animations.plugin.Processing.onPluginTick(Processing.java:69)
        at net.livecar.nuttyworks.destinations_animations.DestAnimations_Plugin$1.run(DestAnimations_Plugin.java:100)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
        at java.lang.Thread.run(Unknown Source)`
