### ISSUE TITLE
issue with sitting an NPC & Sleeping on paper-135

### ISSUE THREAD

**Issue by Nutty101** [Nutty101/NPCDestinations_Animation#7]
java.lang.NullPointerException: null
        at net.livecar.nuttyworks.destinations_animations.storage.Sitting_NPC.StopSitting(Sitting_NPC.java:37) ~[?:?]
        at net.livecar.nuttyworks.destinations_animations.plugin.Processing.undoAnimations(Processing.java:564) ~[?:?]
        at net.livecar.nuttyworks.destinations_animations.DestAnimations_Plugin.npcDespawned(DestAnimations_Plugin.java:124) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor435.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-135]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-135]

**Comment by Nutty101** [comment]
Was resolved prior
