### ISSUE TITLE
[Bug] Console spammed with NullPointerException

### ISSUE THREAD

**Issue by LoneDev6** [Nutty101/NPCDestinations_Animation#8]
Started spamming the console randomly
```
[NPCDestinations_Animator] Error:java.lang.NullPointerException
at net.livecar.nuttyworks.destinations_animations.plugin.Processing.onPluginTick(Processing.java:46)
at net.livecar.nuttyworks.destinations_animations.DestAnimations_Plugin$1.run(DestAnimations_Plugin.java:98)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
at java.lang.Thread.run(Thread.java:748) 
```

NPCDestinations_Animator version 2.3.16

This server is running Paper version git-Paper-246 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by Nutty101** [comment]
2.4.x resolved this one.
